name: ml
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2022.07.19
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libgfortran4=7.5.0
  - libstdcxx-ng=11.2.0
  - pytorch-mutex=1.0
  - libgfortran-ng=7.5.0
  - libgomp=11.2.0
  - mkl=2021.4.0
  - _openmp_mutex=5.1
  - libgcc-ng=11.2.0
  - bzip2=1.0.8
  - cudatoolkit=11.3.1
  - giflib=5.2.1
  - gmp=6.2.1
  - jpeg=9e
  - lame=3.100
  - libffi=3.3
  - libopus=1.3.1
  - libsodium=1.0.18
  - libtasn1=4.16.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - ncurses=6.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.12
  - libidn2=2.3.2
  - libpng=1.6.37
  - nettle=3.7.3
  - readline=8.1.2
  - tk=8.6.12
  - zeromq=4.3.4
  - zstd=1.5.2
  - freetype=2.11.0
  - gnutls=3.6.15
  - libtiff=4.2.0
  - sqlite=3.38.3
  - ffmpeg=4.2.2
  - lcms2=2.12
  - libwebp=1.2.2
  - python=3.7.13
  - backcall=0.2.0
  - certifi=2022.6.15
  - charset-normalizer=2.0.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - idna=3.3
  - nest-asyncio=1.5.5
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.0.1
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pysocks=1.7.1
  - pyzmq=22.3.0
  - six=1.16.0
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - cffi=1.15.0
  - jedi=0.18.1
  - jupyter_core=4.10.0
  - matplotlib-inline=0.1.2
  - mkl-service=2.4.0
  - pexpect=4.8.0
  - prompt-toolkit=3.0.20
  - python-dateutil=2.8.2
  - pytorch=1.11.0
  - setuptools=61.2.0
  - brotlipy=0.7.0
  - cryptography=37.0.1
  - ipython=7.31.1
  - jupyter_client=7.2.2
  - numpy-base=1.21.5
  - pip=21.2.2
  - ipykernel=6.9.1
  - pyopenssl=22.0.0
  - urllib3=1.26.9
  - requests=2.27.1
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.21.5
  - scipy=1.7.3
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip
